api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: "tcp://clinicos_socket_proxy:2375"
    exposedByDefault: false
    network: infrastructure_clinicos_network

log:
  level: INFO
