import dayjs from "dayjs";
import type {
  Patient,
  Doctor,
  Appointment,
  Notification,
  NotificationTemplate,
  AppointmentType,
  AppointmentDuration,
  PaymentMethod,
  StaffMember,
  Conversation,
  Message,
} from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "Sarah Johnson",
    email: "sarah.j@example.com",
    phone: "+1 555 0101",
    gender: "F",
    dob: "1990-03-12",
    notes: "Allergic to penicillin. Mild asthma.",
  },
  {
    id: "p2",
    name: "Michael Chen",
    email: "m.chen@example.com",
    phone: "+1 555 0102",
    gender: "M",
    dob: "1985-07-22",
    notes: "Hypertension, on medication.",
  },
  {
    id: "p3",
    name: "Aisha Patel",
    email: "aisha.p@example.com",
    phone: "+1 555 0103",
    gender: "F",
    dob: "1992-11-04",
    notes: "No known allergies.",
  },
  {
    id: "p4",
    name: "Liam O'Connor",
    email: "liam.oc@example.com",
    phone: "+1 555 0104",
    gender: "M",
    dob: "1978-01-30",
    notes: "Type 2 diabetes.",
  },
  {
    id: "p5",
    name: "Sofia Garcia",
    email: "sofia.g@example.com",
    phone: "+1 555 0105",
    gender: "F",
    dob: "2001-05-18",
    notes: "Routine checkups only.",
  },
  {
    id: "p6",
    name: "Yusuf Ahmed",
    email: "yusuf.a@example.com",
    phone: "+1 555 0106",
    gender: "M",
    dob: "1995-09-09",
    notes: "Recovering from minor surgery.",
  },
  {
    id: "p7",
    name: "Emily Davis",
    email: "emily.d@example.com",
    phone: "+1 555 0107",
    gender: "F",
    dob: "1988-12-25",
    notes: "Pregnancy follow-up.",
  },
  {
    id: "p8",
    name: "Noah Williams",
    email: "noah.w@example.com",
    phone: "+1 555 0108",
    gender: "M",
    dob: "1970-06-14",
    notes: "Cardiac monitoring.",
  },
  {
    id: "p9",
    name: "Maya Rossi",
    email: "maya.r@example.com",
    phone: "+1 555 0109",
    gender: "F",
    dob: "1999-02-28",
    notes: "",
  },
  {
    id: "p10",
    name: "Daniel Kim",
    email: "daniel.k@example.com",
    phone: "+1 555 0110",
    gender: "M",
    dob: "1983-08-08",
    notes: "Migraine history.",
  },
];

export const MOCK_DOCTORS: Doctor[] = [
  {
    id: "d1",
    name: "Dr. Ahmed Benali",
    specialty: "General Practice",
    license: "MD-44128",
    phone: "+1 555 0201",
    email: "a.benali@clinicos.med",
    status: "AVAILABLE",
  },
  {
    id: "d2",
    name: "Dr. Lena Park",
    specialty: "Cardiology",
    license: "MD-77231",
    phone: "+1 555 0202",
    email: "l.park@clinicos.med",
    status: "BUSY",
  },
  {
    id: "d3",
    name: "Dr. Marcus Reed",
    specialty: "Pediatrics",
    license: "MD-39812",
    phone: "+1 555 0203",
    email: "m.reed@clinicos.med",
    status: "AVAILABLE",
  },
  {
    id: "d4",
    name: "Dr. Priya Singh",
    specialty: "Neurology",
    license: "MD-51290",
    phone: "+1 555 0204",
    email: "p.singh@clinicos.med",
    status: "AVAILABLE",
  },
  {
    id: "d5",
    name: "Dr. Olivia Brown",
    specialty: "Orthopedics",
    license: "MD-62018",
    phone: "+1 555 0205",
    email: "o.brown@clinicos.med",
    status: "BUSY",
  },
  {
    id: "d6",
    name: "Dr. Tariq Hassan",
    specialty: "Dermatology",
    license: "MD-83740",
    phone: "+1 555 0206",
    email: "t.hassan@clinicos.med",
    status: "AVAILABLE",
  },
];

const today = dayjs();
function at(day: number, hour: number, minute = 0) {
  return today.add(day, "day").hour(hour).minute(minute).second(0).millisecond(0).toISOString();
}

function mk(
  id: string,
  patientId: string,
  doctorId: string,
  datetime: string,
  reason: string,
  status: Appointment["status"],
  appointmentType: AppointmentType,
  duration: AppointmentDuration,
  notes?: string,
  payment?: PaymentMethod,
): Appointment {
  return {
    id,
    patientId,
    doctorId,
    datetime,
    reason,
    status,
    appointmentType,
    duration,
    notes,
    notifyPatient: true,
    payment,
  };
}

export const MOCK_APPOINTMENTS: Appointment[] = [
  // Today
  mk(
    "a1",
    "p1",
    "d1",
    at(0, 9, 0),
    "Follow-up",
    "SCHEDULED",
    "Follow-up",
    "30 min",
    "Patient reports improvement on new medication.",
    "CNAS",
  ),
  mk(
    "a2",
    "p2",
    "d1",
    at(0, 10, 30),
    "Checkup",
    "SCHEDULED",
    "Checkup",
    "30 min",
    undefined,
    "Cash",
  ),
  mk(
    "a3",
    "p3",
    "d2",
    at(0, 11, 0),
    "Cardiology consult",
    "COMPLETED",
    "Consultation",
    "45 min",
    "ECG normal. Continue current regimen.",
    "Private Insurance",
  ),
  mk(
    "a4",
    "p4",
    "d1",
    at(0, 14, 30),
    "Diabetes review",
    "SCHEDULED",
    "Follow-up",
    "45 min",
    "Bring last 2 weeks of glucose log.",
    "CASNOS",
  ),
  mk(
    "a5",
    "p5",
    "d3",
    at(0, 15, 0),
    "Routine",
    "SCHEDULED",
    "Checkup",
    "15 min",
    undefined,
    "CNAS",
  ),
  mk(
    "a6",
    "p6",
    "d1",
    at(0, 16, 0),
    "Post-op check",
    "SCHEDULED",
    "Follow-up",
    "30 min",
    "Wound healing review.",
    "CNAS",
  ),
  mk(
    "a7",
    "p7",
    "d4",
    at(0, 8, 30),
    "Consultation",
    "CANCELLED",
    "Consultation",
    "1 hour",
    undefined,
    "Cash",
  ),
  // Tomorrow
  mk(
    "a8",
    "p8",
    "d2",
    at(1, 9, 0),
    "Cardiac follow-up",
    "SCHEDULED",
    "Follow-up",
    "45 min",
    "Holter monitor results to review.",
    "Private Insurance",
  ),
  mk(
    "a9",
    "p1",
    "d1",
    at(1, 11, 0),
    "Follow-up",
    "SCHEDULED",
    "Follow-up",
    "30 min",
    undefined,
    "CNAS",
  ),
  mk(
    "a10",
    "p9",
    "d6",
    at(1, 14, 0),
    "Skin consult",
    "SCHEDULED",
    "Consultation",
    "30 min",
    undefined,
    "Cash",
  ),
  // Next 7 days
  mk(
    "a11",
    "p10",
    "d4",
    at(3, 10, 0),
    "Migraine review",
    "SCHEDULED",
    "Follow-up",
    "45 min",
    undefined,
    "CNAS",
  ),
  mk(
    "a12",
    "p1",
    "d1",
    at(5, 14, 30),
    "Routine",
    "SCHEDULED",
    "Checkup",
    "15 min",
    undefined,
    "CNAS",
  ),
  mk(
    "a13",
    "p2",
    "d2",
    at(6, 9, 0),
    "Cardiology",
    "SCHEDULED",
    "Imaging",
    "1 hour",
    "Echocardiogram requested.",
    "Private Insurance",
  ),
  // Past
  mk(
    "a14",
    "p1",
    "d1",
    at(-7, 10, 0),
    "Checkup",
    "COMPLETED",
    "Checkup",
    "30 min",
    "All vitals stable.",
    "CNAS",
  ),
  mk(
    "a15",
    "p1",
    "d1",
    at(-14, 11, 0),
    "Follow-up",
    "COMPLETED",
    "Follow-up",
    "30 min",
    "Asthma controlled.",
    "CNAS",
  ),
  mk(
    "a16",
    "p1",
    "d1",
    at(-30, 9, 30),
    "Consultation",
    "COMPLETED",
    "Consultation",
    "1 hour",
    "Initial intake.",
    "CNAS",
  ),
  mk(
    "a17",
    "p2",
    "d1",
    at(-3, 14, 0),
    "BP review",
    "COMPLETED",
    "Lab Test",
    "15 min",
    "BP 128/82.",
    "Cash",
  ),
  mk(
    "a18",
    "p3",
    "d1",
    at(-5, 15, 0),
    "Routine",
    "COMPLETED",
    "Checkup",
    "15 min",
    undefined,
    "CNAS",
  ),
  mk(
    "a19",
    "p4",
    "d1",
    at(-2, 11, 0),
    "Diabetes",
    "CANCELLED",
    "Follow-up",
    "30 min",
    undefined,
    "CASNOS",
  ),
  mk(
    "a20",
    "p5",
    "d3",
    at(-10, 16, 0),
    "Pediatric checkup",
    "COMPLETED",
    "Checkup",
    "30 min",
    undefined,
    "CNAS",
  ),
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    patientId: "p1",
    message: "Reminder: your appointment is tomorrow at 11:00 with Dr. Benali.",
    channel: "WhatsApp",
    status: "SENT",
    timestamp: dayjs().subtract(1, "hour").toISOString(),
  },
  {
    id: "n2",
    patientId: "p2",
    message: "Your prescription is ready for pickup at the clinic pharmacy.",
    channel: "Email",
    status: "SENT",
    timestamp: dayjs().subtract(3, "hour").toISOString(),
  },
  {
    id: "n3",
    patientId: "p3",
    message: "Your lab results are available in your patient portal.",
    channel: "Email",
    status: "FAILED",
    timestamp: dayjs().subtract(5, "hour").toISOString(),
  },
  {
    id: "n4",
    patientId: "p4",
    message: "Reminder: bring your last 2 weeks of glucose readings to your appointment.",
    channel: "SMS",
    status: "PENDING",
    timestamp: dayjs().subtract(30, "minute").toISOString(),
  },
  {
    id: "n5",
    patientId: "p5",
    message: "Welcome to ClinicOS — manage your appointments online any time.",
    channel: "Email",
    status: "SENT",
    timestamp: dayjs().subtract(8, "hour").toISOString(),
  },
  {
    id: "n6",
    patientId: "p6",
    message: "Your follow-up has been scheduled for Friday at 4:00 PM.",
    channel: "WhatsApp",
    status: "SENT",
    timestamp: dayjs().subtract(12, "hour").toISOString(),
  },
  {
    id: "n7",
    patientId: "p7",
    message: "Your appointment was cancelled. Please reschedule at your convenience.",
    channel: "SMS",
    status: "FAILED",
    timestamp: dayjs().subtract(1, "day").toISOString(),
  },
  {
    id: "n8",
    patientId: "p8",
    message: "Your test results are normal. No further action required.",
    channel: "Email",
    status: "PENDING",
    timestamp: dayjs().subtract(2, "hour").toISOString(),
  },
  {
    id: "n9",
    patientId: "p1",
    message: "Vaccination reminder: annual flu shot is due this month.",
    channel: "WhatsApp",
    status: "SENT",
    timestamp: dayjs().subtract(2, "day").toISOString(),
  },
  {
    id: "n10",
    patientId: "p2",
    message: "How was your visit? Tap to leave feedback.",
    channel: "Email",
    status: "PENDING",
    timestamp: dayjs().subtract(6, "hour").toISOString(),
  },
  {
    id: "n11",
    patientId: "p3",
    message: "Reminder: fasting required before tomorrow's blood work.",
    channel: "SMS",
    status: "SENT",
    timestamp: dayjs().subtract(40, "minute").toISOString(),
  },
  {
    id: "n12",
    patientId: "p10",
    message: "Your migraine review is confirmed for Wednesday at 10:00.",
    channel: "WhatsApp",
    status: "SENT",
    timestamp: dayjs().subtract(15, "minute").toISOString(),
  },
];

export const MOCK_NOTIFICATION_TEMPLATES: NotificationTemplate[] = [
  {
    id: "t1",
    label: "Appointment Reminder",
    body: "Hi {name}, this is a friendly reminder of your upcoming appointment with us. Please reply YES to confirm.",
    channel: "WhatsApp",
    createdAt: dayjs().subtract(20, "day").toISOString(),
  },
  {
    id: "t2",
    label: "Test Results Ready",
    body: "Hi {name}, your recent test results are now available in your patient portal. Please log in to review them.",
    channel: "Email",
    createdAt: dayjs().subtract(15, "day").toISOString(),
  },
  {
    id: "t3",
    label: "Follow-up Due",
    body: "Hi {name}, it's been a while since your last visit. Please book a follow-up appointment at your convenience.",
    channel: "SMS",
    createdAt: dayjs().subtract(8, "day").toISOString(),
  },
];

export const DEMO_USERS: Record<
  string,
  { role: "ADMIN" | "DOCTOR" | "RECEPTIONIST" | "PATIENT"; name: string; email: string }
> = {
  ADMIN: { role: "ADMIN", name: "Alex Morgan", email: "admin@clinicos.med" },
  DOCTOR: { role: "DOCTOR", name: "Dr. Ahmed Benali", email: "a.benali@clinicos.med" },
  RECEPTIONIST: { role: "RECEPTIONIST", name: "Jamie Lee", email: "reception@clinicos.med" },
  PATIENT: { role: "PATIENT", name: "Sarah Johnson", email: "sarah.j@example.com" },
};

// ============= Messaging mock data =============
export const MOCK_STAFF: StaffMember[] = [
  { id: "admin", name: "Alex Morgan", role: "ADMIN", online: true },
  {
    id: "d1",
    name: "Dr. Ahmed Benali",
    role: "DOCTOR",
    specialty: "General Practice",
    online: true,
  },
  {
    id: "d2",
    name: "Dr. Lena Park",
    role: "DOCTOR",
    specialty: "Cardiology",
    online: false,
    lastSeen: dayjs().subtract(23, "minute").toISOString(),
  },
  {
    id: "d3",
    name: "Dr. Marcus Reed",
    role: "DOCTOR",
    specialty: "Pediatrics",
    online: false,
    lastSeen: dayjs().subtract(2, "hour").toISOString(),
  },
  { id: "d4", name: "Dr. Priya Singh", role: "DOCTOR", specialty: "Neurology", online: true },
  { id: "r1", name: "Jamie Lee", role: "RECEPTIONIST", online: true },
  {
    id: "r2",
    name: "Karim Oussama",
    role: "RECEPTIONIST",
    online: false,
    lastSeen: dayjs().subtract(45, "minute").toISOString(),
  },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "c1",
    type: "DIRECT",
    participantIds: ["admin", "d1"],
    lastActivity: dayjs().subtract(5, "minute").toISOString(),
    pinned: true,
  },
  {
    id: "c2",
    type: "GROUP",
    name: "Medical Staff",
    participantIds: ["admin", "d1", "d2", "d3", "d4"],
    lastActivity: dayjs().subtract(30, "minute").toISOString(),
    pinned: true,
  },
  {
    id: "c3",
    type: "GROUP",
    name: "Clinic Operations",
    participantIds: ["admin", "r1", "r2"],
    lastActivity: dayjs().subtract(1, "hour").toISOString(),
    pinned: false,
  },
  {
    id: "c4",
    type: "DIRECT",
    participantIds: ["admin", "r1"],
    lastActivity: dayjs().subtract(3, "hour").toISOString(),
    pinned: false,
  },
  {
    id: "c5",
    type: "DIRECT",
    participantIds: ["d1", "r1"],
    lastActivity: dayjs().subtract(2, "hour").toISOString(),
    pinned: false,
  },
];

export const MOCK_MESSAGES: Message[] = [
  // c1 — admin ↔ d1
  {
    id: "m1",
    conversationId: "c1",
    senderId: "d1",
    content:
      "Good morning! Can you check Mr. Karim's file before 10am? He's coming for a follow-up.",
    sentAt: dayjs().subtract(20, "minute").toISOString(),
    readBy: ["d1"],
  },
  {
    id: "m2",
    conversationId: "c1",
    senderId: "admin",
    content: "Sure, I'll pull it up now. Do you need any labs ordered?",
    sentAt: dayjs().subtract(18, "minute").toISOString(),
    readBy: ["admin", "d1"],
  },
  {
    id: "m3",
    conversationId: "c1",
    senderId: "d1",
    content: "Yes, CBC and lipid panel please. Thanks!",
    sentAt: dayjs().subtract(5, "minute").toISOString(),
    readBy: ["d1"],
  },
  // c2 — Medical Staff
  {
    id: "m4",
    conversationId: "c2",
    senderId: "admin",
    content: "Reminder: Staff meeting this Friday at 14:00 in the conference room.",
    sentAt: dayjs().subtract(1, "hour").toISOString(),
    readBy: ["admin", "d1"],
  },
  {
    id: "m5",
    conversationId: "c2",
    senderId: "d2",
    content: "Confirmed, I'll be there.",
    sentAt: dayjs().subtract(50, "minute").toISOString(),
    readBy: ["admin", "d1", "d2"],
  },
  {
    id: "m6",
    conversationId: "c2",
    senderId: "d1",
    content: "Same, see everyone Friday 👍",
    sentAt: dayjs().subtract(30, "minute").toISOString(),
    readBy: ["admin", "d1"],
  },
  // c3 — Clinic Operations
  {
    id: "m7",
    conversationId: "c3",
    senderId: "r1",
    content: "The printer in reception is out of paper again. Can someone restock?",
    sentAt: dayjs().subtract(2, "hour").toISOString(),
    readBy: ["r1"],
  },
  {
    id: "m8",
    conversationId: "c3",
    senderId: "admin",
    content: "On it, restocking now.",
    sentAt: dayjs().subtract(1, "hour").toISOString(),
    readBy: ["admin", "r1"],
  },
  // c4 — admin ↔ r1
  {
    id: "m9",
    conversationId: "c4",
    senderId: "r1",
    content: "Admin, Dr. Ahmed's 3pm patient called to reschedule. Should I move it to tomorrow?",
    sentAt: dayjs().subtract(3, "hour").toISOString(),
    readBy: ["admin", "r1"],
  },
  {
    id: "m10",
    conversationId: "c4",
    senderId: "admin",
    content: "Yes go ahead, same time tomorrow is fine.",
    sentAt: dayjs().subtract(3, "hour").toISOString(),
    readBy: ["admin", "r1"],
  },
  // c5 — d1 ↔ r1
  {
    id: "m11",
    conversationId: "c5",
    senderId: "r1",
    content: "Doctor, your 4pm has arrived early.",
    sentAt: dayjs().subtract(2, "hour").toISOString(),
    readBy: ["d1", "r1"],
  },
  {
    id: "m12",
    conversationId: "c5",
    senderId: "d1",
    content: "Thanks, send them in 10 minutes.",
    sentAt: dayjs().subtract(2, "hour").add(2, "minute").toISOString(),
    readBy: ["d1", "r1"],
  },
];
